# Generated by Django 5.2.13 on 2026-04-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_audio_path', models.CharField(blank=True, default='', max_length=500)),
                ('transcription', models.TextField(blank=True, default='')),
                ('relevance_score', models.FloatField(default=0)),
                ('eye_contact_score', models.FloatField(default=0)),
                ('emotion_score', models.FloatField(default=0)),
                ('voice_stress_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('emotions_detected', models.JSONField(default=dict)),
                ('eye_contact_frames', models.IntegerField(default=0)),
                ('tension_level', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('eye_contact', models.BooleanField()),
                ('timestamp', models.FloatField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_frames', to='interview.answer')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('resume_text', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(default=0)),
                ('recommendation', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('expected_keywords', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewsession')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview.question'),
        ),
    ]
